import type { Letter } from '@/types/content';

// The 28 letters of the Arabic alphabet (hurūf al-hijā'iyyah) with each
// letter's fatḥah / kasrah / ḍammah form, English + Bangla pronunciation,
// and (for ا و ي) the long-vowel companion.

export const LETTERS: Letter[] = [
  {
    order: 1,
    slug: 'alif',
    arabic: 'ا',
    name: 'Alif',
    englishSound: 'Aa / A',
    banglaSound: 'আলিফ (আ)',
    category: 'vowel',
    fatha: { arabic: 'أَ', english: 'a', bangla: 'আ' },
    kasra: { arabic: 'إِ', english: 'i', bangla: 'ই' },
    damma: { arabic: 'أُ', english: 'u', bangla: 'উ' },
    longVowel: { arabic: 'ا', english: 'ā (aa)', bangla: 'আ (দীর্ঘ)' },
  },
  {
    order: 2,
    slug: 'ba',
    arabic: 'ب',
    name: 'Bā',
    englishSound: 'B',
    banglaSound: 'বা',
    fatha: { arabic: 'بَ', english: 'ba', bangla: 'বা' },
    kasra: { arabic: 'بِ', english: 'bi', bangla: 'বি' },
    damma: { arabic: 'بُ', english: 'bu', bangla: 'বু' },
  },
  {
    order: 3,
    slug: 'ta',
    arabic: 'ت',
    name: 'Tā',
    englishSound: 'T',
    banglaSound: 'তা',
    fatha: { arabic: 'تَ', english: 'ta', bangla: 'তা' },
    kasra: { arabic: 'تِ', english: 'ti', bangla: 'তি' },
    damma: { arabic: 'تُ', english: 'tu', bangla: 'তু' },
  },
  {
    order: 4,
    slug: 'tha',
    arabic: 'ث',
    name: 'Thā',
    englishSound: 'Th (as in “think”)',
    banglaSound: 'ছা / থা (ইংরেজি "think"-এর "th")',
    englishNote: 'Unvoiced "th" like in *thin*, not *this*.',
    banglaNote: 'দাঁতের ফাঁকে জিহ্বা রেখে বলো — ইংরেজি "th" এর মতো।',
    fatha: { arabic: 'ثَ', english: 'tha', bangla: 'ছা / থা' },
    kasra: { arabic: 'ثِ', english: 'thi', bangla: 'ছি / থি' },
    damma: { arabic: 'ثُ', english: 'thu', bangla: 'ছু / থু' },
  },
  {
    order: 5,
    slug: 'jim',
    arabic: 'ج',
    name: 'Jīm',
    englishSound: 'J (as in “jam”)',
    banglaSound: 'জীম (জা)',
    fatha: { arabic: 'جَ', english: 'ja', bangla: 'জা' },
    kasra: { arabic: 'جِ', english: 'ji', bangla: 'জি' },
    damma: { arabic: 'جُ', english: 'ju', bangla: 'জু' },
  },
  {
    order: 6,
    slug: 'hha',
    arabic: 'ح',
    name: 'Ḥā',
    englishSound: 'Deep H (from the throat)',
    banglaSound: 'হা (গলা থেকে)',
    category: 'guttural',
    englishNote: 'A strong "H" produced deep in the throat.',
    banglaNote: 'গলার ভেতর থেকে চাপ দিয়ে বলো — সাধারণ "হ" নয়।',
    fatha: { arabic: 'حَ', english: 'ḥa', bangla: 'হা (গলার)' },
    kasra: { arabic: 'حِ', english: 'ḥi', bangla: 'হি (গলার)' },
    damma: { arabic: 'حُ', english: 'ḥu', bangla: 'হু (গলার)' },
  },
  {
    order: 7,
    slug: 'kha',
    arabic: 'خ',
    name: 'Khā',
    englishSound: 'Kh (as in Bach)',
    banglaSound: 'খা (গলা থেকে)',
    category: 'guttural',
    englishNote: 'Like the "ch" in German *Bach* or Scottish *loch*.',
    banglaNote: 'গলার পিছন থেকে ঘষে বের হওয়া "খ"।',
    fatha: { arabic: 'خَ', english: 'kha', bangla: 'খা' },
    kasra: { arabic: 'خِ', english: 'khi', bangla: 'খি' },
    damma: { arabic: 'خُ', english: 'khu', bangla: 'খু' },
  },
  {
    order: 8,
    slug: 'dal',
    arabic: 'د',
    name: 'Dāl',
    englishSound: 'D',
    banglaSound: 'দাল',
    fatha: { arabic: 'دَ', english: 'da', bangla: 'দা' },
    kasra: { arabic: 'دِ', english: 'di', bangla: 'দি' },
    damma: { arabic: 'دُ', english: 'du', bangla: 'দু' },
  },
  {
    order: 9,
    slug: 'dhal',
    arabic: 'ذ',
    name: 'Dhāl',
    englishSound: 'Th (as in “this”)',
    banglaSound: 'যাল / ধ (ইংরেজি "th"-এর নরম রূপ)',
    englishNote: 'Voiced "th" like in *this*, *that*.',
    banglaNote: 'দাঁতে জিভ ছুঁইয়ে ঘষা "দ্‌হ"।',
    fatha: { arabic: 'ذَ', english: 'dha', bangla: 'ধা' },
    kasra: { arabic: 'ذِ', english: 'dhi', bangla: 'ধি' },
    damma: { arabic: 'ذُ', english: 'dhu', bangla: 'ধু' },
  },
  {
    order: 10,
    slug: 'ra',
    arabic: 'ر',
    name: 'Rā',
    englishSound: 'Rolled R',
    banglaSound: 'রা',
    englishNote: 'A short trilled/rolled R (like Spanish or Italian).',
    banglaNote: 'জিভ কাঁপিয়ে রোল করা "র"।',
    fatha: { arabic: 'رَ', english: 'ra', bangla: 'রা' },
    kasra: { arabic: 'رِ', english: 'ri', bangla: 'রি' },
    damma: { arabic: 'رُ', english: 'ru', bangla: 'রু' },
  },
  {
    order: 11,
    slug: 'zay',
    arabic: 'ز',
    name: 'Zāy',
    englishSound: 'Z',
    banglaSound: 'যায়',
    fatha: { arabic: 'زَ', english: 'za', bangla: 'যা' },
    kasra: { arabic: 'زِ', english: 'zi', bangla: 'যি' },
    damma: { arabic: 'زُ', english: 'zu', bangla: 'যু' },
  },
  {
    order: 12,
    slug: 'sin',
    arabic: 'س',
    name: 'Sīn',
    englishSound: 'S',
    banglaSound: 'সীন',
    fatha: { arabic: 'سَ', english: 'sa', bangla: 'সা' },
    kasra: { arabic: 'سِ', english: 'si', bangla: 'সি' },
    damma: { arabic: 'سُ', english: 'su', bangla: 'সু' },
  },
  {
    order: 13,
    slug: 'shin',
    arabic: 'ش',
    name: 'Shīn',
    englishSound: 'Sh',
    banglaSound: 'শীন',
    fatha: { arabic: 'شَ', english: 'sha', bangla: 'শা' },
    kasra: { arabic: 'شِ', english: 'shi', bangla: 'শি' },
    damma: { arabic: 'شُ', english: 'shu', bangla: 'শু' },
  },
  {
    order: 14,
    slug: 'saad',
    arabic: 'ص',
    name: 'Ṣād',
    englishSound: 'Heavy S',
    banglaSound: 'সাদ (মোটা "স")',
    category: 'heavy',
    englishNote: 'An emphatic "S" — thick, back-of-mouth quality.',
    banglaNote: 'মুখ ভরে মোটা করে "স"।',
    fatha: { arabic: 'صَ', english: 'ṣa', bangla: 'সা (মোটা)' },
    kasra: { arabic: 'صِ', english: 'ṣi', bangla: 'সি (মোটা)' },
    damma: { arabic: 'صُ', english: 'ṣu', bangla: 'সু (মোটা)' },
  },
  {
    order: 15,
    slug: 'daad',
    arabic: 'ض',
    name: 'Ḍād',
    englishSound: 'Heavy D',
    banglaSound: 'দাদ (মোটা "দ")',
    category: 'heavy',
    englishNote: 'Emphatic "D" — deep, thick, jaw-forward.',
    banglaNote: 'জিভের এক পাশ তালুতে চেপে মোটা "দ"।',
    fatha: { arabic: 'ضَ', english: 'ḍa', bangla: 'দা (মোটা)' },
    kasra: { arabic: 'ضِ', english: 'ḍi', bangla: 'দি (মোটা)' },
    damma: { arabic: 'ضُ', english: 'ḍu', bangla: 'দু (মোটা)' },
  },
  {
    order: 16,
    slug: 'taa',
    arabic: 'ط',
    name: 'Ṭā',
    englishSound: 'Heavy T',
    banglaSound: 'তোয়া (মোটা "ত")',
    category: 'heavy',
    englishNote: 'Emphatic "T" — thick, back-of-mouth, jaw-forward.',
    banglaNote: 'জিভ চেপে ধরে মোটা "ত"।',
    fatha: { arabic: 'طَ', english: 'ṭa', bangla: 'তা (মোটা)' },
    kasra: { arabic: 'طِ', english: 'ṭi', bangla: 'তি (মোটা)' },
    damma: { arabic: 'طُ', english: 'ṭu', bangla: 'তু (মোটা)' },
  },
  {
    order: 17,
    slug: 'zaa',
    arabic: 'ظ',
    name: 'Ẓā',
    englishSound: 'Heavy Dh / Z',
    banglaSound: 'যোয়া / যা (মোটা)',
    category: 'heavy',
    englishNote: 'Emphatic voiced "th" (as in *this*) — thick, from the back.',
    banglaNote: 'দাঁতে জিভ ছুঁইয়ে মোটা "য" — খুব সাবধানে।',
    fatha: { arabic: 'ظَ', english: 'ẓa', bangla: 'যা (মোটা)' },
    kasra: { arabic: 'ظِ', english: 'ẓi', bangla: 'যি (মোটা)' },
    damma: { arabic: 'ظُ', english: 'ẓu', bangla: 'যু (মোটা)' },
  },
  {
    order: 18,
    slug: 'ayn',
    arabic: 'ع',
    name: '‘Ayn',
    englishSound: 'Deep throat sound',
    banglaSound: 'আইন (গলার স্বর)',
    category: 'guttural',
    englishNote: 'A voiced pharyngeal — imagine "a" produced deep in the throat.',
    banglaNote: 'গলার ভেতর চাপ দিয়ে "আ" জাতীয় ধ্বনি।',
    fatha: { arabic: 'عَ', english: '‘a', bangla: 'আ (গলার)' },
    kasra: { arabic: 'عِ', english: '‘i', bangla: 'ই (গলার)' },
    damma: { arabic: 'عُ', english: '‘u', bangla: 'উ (গলার)' },
  },
  {
    order: 19,
    slug: 'ghayn',
    arabic: 'غ',
    name: 'Ghayn',
    englishSound: 'Gh (gargled)',
    banglaSound: 'গইন / ঘইন',
    category: 'guttural',
    englishNote: 'Like French "R" or a gargled "gh".',
    banglaNote: 'গলার ভেতর থেকে গড়গড় "ঘ"।',
    fatha: { arabic: 'غَ', english: 'gha', bangla: 'ঘা' },
    kasra: { arabic: 'غِ', english: 'ghi', bangla: 'ঘি' },
    damma: { arabic: 'غُ', english: 'ghu', bangla: 'ঘু' },
  },
  {
    order: 20,
    slug: 'fa',
    arabic: 'ف',
    name: 'Fā',
    englishSound: 'F',
    banglaSound: 'ফা',
    fatha: { arabic: 'فَ', english: 'fa', bangla: 'ফা' },
    kasra: { arabic: 'فِ', english: 'fi', bangla: 'ফি' },
    damma: { arabic: 'فُ', english: 'fu', bangla: 'ফু' },
  },
  {
    order: 21,
    slug: 'qaf',
    arabic: 'ق',
    name: 'Qāf',
    englishSound: 'Deep K / Q',
    banglaSound: 'ক্বাফ (গলা থেকে "ক")',
    category: 'heavy',
    englishNote: 'A "K" produced far back near the uvula.',
    banglaNote: 'গলার ভেতরে চাপ দিয়ে মোটা "ক"।',
    fatha: { arabic: 'قَ', english: 'qa', bangla: 'ক্বা' },
    kasra: { arabic: 'قِ', english: 'qi', bangla: 'ক্বি' },
    damma: { arabic: 'قُ', english: 'qu', bangla: 'ক্বু' },
  },
  {
    order: 22,
    slug: 'kaf',
    arabic: 'ك',
    name: 'Kāf',
    englishSound: 'K',
    banglaSound: 'কাফ',
    fatha: { arabic: 'كَ', english: 'ka', bangla: 'কা' },
    kasra: { arabic: 'كِ', english: 'ki', bangla: 'কি' },
    damma: { arabic: 'كُ', english: 'ku', bangla: 'কু' },
  },
  {
    order: 23,
    slug: 'lam',
    arabic: 'ل',
    name: 'Lām',
    englishSound: 'L',
    banglaSound: 'লাম',
    fatha: { arabic: 'لَ', english: 'la', bangla: 'লা' },
    kasra: { arabic: 'لِ', english: 'li', bangla: 'লি' },
    damma: { arabic: 'لُ', english: 'lu', bangla: 'লু' },
  },
  {
    order: 24,
    slug: 'mim',
    arabic: 'م',
    name: 'Mīm',
    englishSound: 'M',
    banglaSound: 'মীম',
    fatha: { arabic: 'مَ', english: 'ma', bangla: 'মা' },
    kasra: { arabic: 'مِ', english: 'mi', bangla: 'মি' },
    damma: { arabic: 'مُ', english: 'mu', bangla: 'মু' },
  },
  {
    order: 25,
    slug: 'nun',
    arabic: 'ن',
    name: 'Nūn',
    englishSound: 'N',
    banglaSound: 'নূন',
    fatha: { arabic: 'نَ', english: 'na', bangla: 'না' },
    kasra: { arabic: 'نِ', english: 'ni', bangla: 'নি' },
    damma: { arabic: 'نُ', english: 'nu', bangla: 'নু' },
  },
  {
    order: 26,
    slug: 'ha',
    arabic: 'ه',
    name: 'Hā',
    englishSound: 'H (soft)',
    banglaSound: 'হা',
    fatha: { arabic: 'هَ', english: 'ha', bangla: 'হা' },
    kasra: { arabic: 'هِ', english: 'hi', bangla: 'হি' },
    damma: { arabic: 'هُ', english: 'hu', bangla: 'হু' },
  },
  {
    order: 27,
    slug: 'waw',
    arabic: 'و',
    name: 'Wāw',
    englishSound: 'W / Oo',
    banglaSound: 'ওয়াও',
    category: 'vowel',
    fatha: { arabic: 'وَ', english: 'wa', bangla: 'ওয়া' },
    kasra: { arabic: 'وِ', english: 'wi', bangla: 'উই' },
    damma: { arabic: 'وُ', english: 'wu', bangla: 'উ' },
    longVowel: { arabic: 'و', english: 'ū (oo)', bangla: 'ঊ / উ (দীর্ঘ)' },
  },
  {
    order: 28,
    slug: 'ya',
    arabic: 'ي',
    name: 'Yā',
    englishSound: 'Y / Ee',
    banglaSound: 'ইয়া',
    category: 'vowel',
    fatha: { arabic: 'يَ', english: 'ya', bangla: 'ইয়া' },
    kasra: { arabic: 'يِ', english: 'yi', bangla: 'ইই' },
    damma: { arabic: 'يُ', english: 'yu', bangla: 'ইউ' },
    longVowel: { arabic: 'ي', english: 'ī (ee)', bangla: 'ঈ / ই (দীর্ঘ)' },
  },
];

export function getLetter(slug: string): Letter | undefined {
  return LETTERS.find((l) => l.slug === slug);
}

export function getLetterNeighbours(slug: string) {
  const i = LETTERS.findIndex((l) => l.slug === slug);
  return {
    prev: i > 0 ? LETTERS[i - 1] : null,
    next: i >= 0 && i < LETTERS.length - 1 ? LETTERS[i + 1] : null,
  };
}

// Harakat reference for the explainer sections.

export const BASIC_HARAKAT = [
  {
    id: 'fatha',
    arabic: 'ـَ',
    name: 'Fatḥah',
    banglaName: 'ফাতহা',
    example: 'بَ',
    sound: 'a',
    bangla: 'আ / অ',
  },
  {
    id: 'kasra',
    arabic: 'ـِ',
    name: 'Kasrah',
    banglaName: 'কাসরা',
    example: 'بِ',
    sound: 'i',
    bangla: 'ই',
  },
  {
    id: 'damma',
    arabic: 'ـُ',
    name: 'Ḍammah',
    banglaName: 'দাম্মা',
    example: 'بُ',
    sound: 'u',
    bangla: 'উ',
  },
];

export const OTHER_MARKS = [
  {
    id: 'sukun',
    arabic: 'ـْ',
    name: 'Sukūn',
    banglaName: 'সুকুন',
    english: 'No vowel — the letter is bare',
    bangla: 'কোনো স্বর নেই',
  },
  {
    id: 'shadda',
    arabic: 'ـّ',
    name: 'Shaddah',
    banglaName: 'শাদ্দাহ',
    english: 'Double the consonant',
    bangla: 'দুই বার উচ্চারণ (ব্যঞ্জন দ্বিগুণ)',
  },
  {
    id: 'fathatan',
    arabic: 'ـً',
    name: 'Fatḥatain',
    banglaName: 'ফাতহাতাইন',
    english: 'an',
    bangla: 'আন',
  },
  {
    id: 'kasratan',
    arabic: 'ـٍ',
    name: 'Kasratain',
    banglaName: 'কাসরাতাইন',
    english: 'in',
    bangla: 'ইন',
  },
  {
    id: 'dammatan',
    arabic: 'ـٌ',
    name: 'Ḍammatain',
    banglaName: 'দাম্মাতাইন',
    english: 'un',
    bangla: 'উন',
  },
];

export const LONG_VOWELS = [
  { arabic: 'ا', english: 'ā (aa)', bangla: 'আ' },
  { arabic: 'و', english: 'ū (oo)', bangla: 'ঊ / উ' },
  { arabic: 'ي', english: 'ī (ee)', bangla: 'ঈ / ই' },
];
